### ISSUE TITLE
Format code function remove blocknumber

### ISSUE THREAD

**Issue by AurelWM** [isg-stuttgart/vscode-isg-cnc#10]
**Bug observed**
Format code function remove blocknumber if there is no comment after it.

**To Reproduce**
Before Format code:
![image](https://user-images.githubusercontent.com/94175716/142154365-430df89c-a655-4c62-ad63-bc5cc22fdc02.png)

After 
![image](https://user-images.githubusercontent.com/94175716/142154513-b8ac70b3-0069-448e-bb1c-bbfc134c0fcf.png)

Thank you, best regards

**Comment by andreashafner-isg** [comment]
Thanks for reporting @AurelWM. Version V0.2.5 is out now with the fix.
