### ISSUE TITLE
Wrong display in sidebar for program calls

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#104]
**Describe the bug**
The sidebar display lines of the nc-program without a program call.

**To Reproduce**
Create a CNC file with:

```
N8380           V.L.KARD_WKL = 50 
N8390           V.L.KARD_WKL = V.DB.SPDL[48]

%L .createTableLinkpoints

%L .setObjects

```

**Expected behavior**
No program call is displayed in the sidebar.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/85152900/212952263-59fafe6d-d912-4be5-8048-dcacf79d88e9.png)

**Comment by jurekseverin-isg** [comment]
This was fixed within https://github.com/isg-stuttgart/vscode-isg-cnc/pull/106
