### ISSUE TITLE
"Go to reference" for program declarations, goto-labels and local variable declarations

### ISSUE THREAD

**Issue by jurekseverin-isg** [isg-stuttgart/vscode-isg-cnc#108]
Implement the "Go To Reference" feature for the mentioned syntax elements.

**Comment by jurekseverin-isg** [comment]
@georgulbrich-isg @lukashettler-isg 
Do we want to include the definition line itself in the listing of references?
E.g. should we insert `%L cycle` at the position of the drawed arrow?
![Screenshot 2023-03-25 235405](https://user-images.githubusercontent.com/102800599/227746194-0d075cc2-1b1c-4be4-abd0-0b1958b9f5de.png)
Pro: User can use this to jump to the definition without more clicks after scrolling through references) and at least the default Typescript Language Server seems to include them (see following function-definition)
![function](https://user-images.githubusercontent.com/102800599/227746292-909c8ee5-158d-4e65-a2f6-f8ea85747db8.png)
Contra: In my opinion "Definitions" are no "References", as others also think: https://github.com/microsoft/vscode/issues/68071

**Comment by lukashettler-isg** [comment]
> @georgulbrich-isg @lukashettler-isg Do we want to include the definition line itself in the listing of references? E.g. should we insert `%L cycle` at the position of the drawed arrow? ![Screenshot 2023-03-25 235405](https://user-images.githubusercontent.com/102800599/227746194-0d075cc2-1b1c-4be4-abd0-0b1958b9f5de.png) Pro: User can use this to jump to the definition without more clicks after scrolling through references) and at least the default Typescript Language Server seems to include them (see following function-definition) ![function](https://user-images.githubusercontent.com/102800599/227746292-909c8ee5-158d-4e65-a2f6-f8ea85747db8.png) Contra: In my opinion "Definitions" are no "References", as others also think: [microsoft/vscode#68071](https://github.com/microsoft/vscode/issues/68071)

I would prefer the list without the definition because we have the _Go to definition_ feature. This should be comfortable enough to find the definition fast. And the definition is not a reference...

**Comment by georgulbrich-isg** [comment]
Either way fine with me.

**Comment by jurekseverin-isg** [comment]
Close as completed in https://github.com/isg-stuttgart/vscode-isg-cnc/pull/115
