### ISSUE TITLE
Go To definition not working for global cycle calls

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#110]
**Describe the bug**

The go to definition functionality doesn't find global programs in the working space.

**To Reproduce**

With this folder structure the go to definition functionality **doesn't** find subPrograms.nc.

![grafik](https://user-images.githubusercontent.com/85152900/226629040-cc6c1589-32f0-4bad-bd84-fa7effa05a4a.png)

With this folder structure the go to definition functionality **does** find subPrograms.nc.

![grafik](https://user-images.githubusercontent.com/85152900/226629495-568cb547-492c-4f13-8d9a-ee7408d2e37a.png)

**Comment by jurekseverin-isg** [comment]
Fixed in https://github.com/isg-stuttgart/vscode-isg-cnc/pull/112
