### ISSUE TITLE
feature request for Go to reference

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#111]
it would be helpful to have a listing of cycles/subcycles/programs/subprograms in which the selected variable/cycle/program is located in the workspace.
![grafik](https://user-images.githubusercontent.com/101697940/227235621-488fc9a5-f69a-4450-aafc-4b60c9076bb1.png)

Furthermore, by clicking on one of the e.g. cycles in the listing in the workspace, the cycle should open and refer to the appropriate place.
![grafik](https://user-images.githubusercontent.com/101697940/227236098-838db80e-62ba-4c22-a5cd-d0f4e0f86a71.png)

**Comment by jurekseverin-isg** [comment]
I am not quite shure if i understood everything correctly. Here is what i got with generic file names:

`calledProgram.nc` is a program which i call in three different workspace locations namely: `callingProgram1.nc`, `callingProgram2.nc` and `callingProgram3.nc`.

If i understand you correctly you e.g. want to select the call `L calledProgram.nc` within `callingProgram1.nc`. Then you want the sidebar to show each position which uses `calledProgram.nc`, also giving the possibility to jump there via click.

If that's all, this is done by the normal "Go to References" feature and will look like this (by shift+F12 on `L calledProgram.nc` within `callingProgram1.nc`) :
![Screenshot 2023-03-25 224513](https://user-images.githubusercontent.com/102800599/227744196-a385643d-1d44-4585-96f7-405d68e36541.png)


In this view you can click on one of the references (e.g. the underligned appearence in `callingProgram3.nc`) and its context will show inline (blue background).
When double clicking the reference you will jump into the respective file to the respective location instead (as requested in your second image).
Therefore i don't see the need of involving the sidebar here. 
If i didn't understand you correctly please correct me.

**Comment by georgulbrich-isg** [comment]
Maybe @rosariotaormina-isg was, just as me, unaware of the power of the "Go To References" feature. I think this standard feature is enough. We can keep the sidebar for ISG features that are not represented in VSCode standard mechanisms.

**Comment by jurekseverin-isg** [comment]
Then i will close this issue as it is contained within https://github.com/isg-stuttgart/vscode-isg-cnc/issues/108
