### ISSUE TITLE
V.CYC. - Variables are not recognized

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#119]
unlike the V.L variables, the V.CYC. variables are not recognized

![grafik](https://user-images.githubusercontent.com/101697940/229135820-9e3bb9ed-5cbf-46b9-b404-4eca3e8b4a88.png)

**Comment by andreas-hafner** [comment]
It looks like the CYC part is missing in the ncParser.ts line 377ff.

**Comment by jurekseverin-isg** [comment]
I missed these type of variables when reading the documentation. V.CYC variables are added in the grammar now which also includes them in Go To Definition/References. 
Thanks for reporting.

Closed with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/123
