### ISSUE TITLE
if something is immediately in front of the variable, it is not recognized

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#120]
if something is immediately in front of the variable, it is not recognized
![grafik](https://user-images.githubusercontent.com/101697940/229136806-c3ee4e6a-2f0f-4732-ad68-32c3177d5924.png)

**Comment by jurekseverin-isg** [comment]
References and Definitions for variables (and only for these) are searched by string search with next release. Therethrough this problem should no longer occur.

See https://github.com/isg-stuttgart/vscode-isg-cnc/pull/130
