### ISSUE TITLE
specification of path for "go to reference" would be helpful

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#121]
When we autotest locally, non-relevant folders are created for the git repository where there may be non-updated files. The hierarchy is currently searched from top to bottom and thus irrelevant files are found. If you could specify search paths you would reduce it to the files that matter

**Comment by rosariotaormina-isg** [comment]
That would also be a nice solution

**Comment by jurekseverin-isg** [comment]
An ignore file for this was added to the new Versions 0.4.4. After the update comes, see the README.md for using instructions.

Closed by https://github.com/isg-stuttgart/vscode-isg-cnc/pull/131
