### ISSUE TITLE
Go to fileoffset in selected file

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#149]
This feature should find a cnc program in the current working space and jump directly to the given fileoffset. With multi selection enabled in VS Code it's possible to mark the cnc program and the fileoffset. The feature should take this information and jump to the program. In the following picture an example is shown, how the input for the functionality could be selected.

![grafik](https://github.com/isg-stuttgart/vscode-isg-cnc/assets/85152900/f43e1e94-9951-4463-953a-93fe36842346)

**Comment by lukashettler-isg** [comment]
@rosariotaormina-isg 
 fit the description above to your requirements?

**Comment by jurekseverin-isg** [comment]
Feature completed with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/156
