### ISSUE TITLE
Wrong insertion of N-numbers

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#158]
**Describe the bug**
When executing the command add N-numbers the numbers are wrong inserted. A number is inserted before the program name (line with % at the beginning) and a number is inserted in a multiline. Both insertion lead to a wrong nc-program.

**To Reproduce**
Execute add N-numbers in following nc-program

```
; %Test - Achsen

%Test - Achsen

N020 G90 A1 = 0

N5100 #MC_MovePath SYN	[ CH=   \
                          @PL1=V.P.Appr_Start_ACS_X @PL2=V.P.Appr_Start_ACS_Y @PL3=V.P.Appr_Start_ACS_Z ]
                          
N200 M30
```

**Comment by jurekseverin-isg** [comment]
Closed with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/162
