### ISSUE TITLE
Add encryption for CNC files

### ISSUE THREAD

**Issue by ghost** [isg-stuttgart/vscode-isg-cnc#16]
Add possibilities to encrypt or decrypt an CNC file with password.

**Comment by JurekSeverin** [comment]
Current status: First version of blowfish algorithm will be tested soon in a seperate project via unit tests.
The user interface integration of blowfish is written and will be tested, improved and pushed after succesful unit tests of blowfish.

**Comment by jurekseverin-isg** [comment]
This feature was published in the newest version
