### ISSUE TITLE
Update cycle.json

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#160]
We got a new description for the CNC-cycles.

[cycles.json](https://github.com/user-attachments/files/17645230/cycles.json)

**Comment by jurekseverin-isg** [comment]
Closed with
https://github.com/isg-stuttgart/vscode-isg-cnc/pull/163
https://github.com/isg-stuttgart/vscode-isg-cnc/pull/161
