### ISSUE TITLE
File missing docs\images\subProgramComment.png

### ISSUE THREAD

**Issue by asteding** [isg-stuttgart/vscode-isg-cnc#165]
**Describe the bug**
A file `docs\images\subProgramComment.png` is missing causing a 404.

**To Reproduce**
1. Click the Link https://github.com/isg-stuttgart/vscode-isg-cnc/blob/main/docs%5Cimages%5CsubProgramComment.png

**Expected behavior**
Show the picture instead of a 404.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/2c4e3f93-5dbd-4812-8d9a-23f4201609d1)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
 - Version: 132.0.2

**Additional context**
Why is any information about my phone needed?

**Comment by jurekseverin-isg** [comment]
Closed with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/166

**Comment by jurekseverin-isg** [comment]
@andreassteding-isg Thanks for reporting. The Problem is fixed and the picture will be visible on the next release.
