### ISSUE TITLE
Syntax highlight without ISG Themes

### ISSUE THREAD

**Issue by mpacher** [isg-stuttgart/vscode-isg-cnc#18]
I would like to ask to make the syntax highlight work without forcing the user to select the "ISG Light/Dark" themes. To me this is really disturbing because I have different projects written in different programming languages and I do not want to be forced in choosing your themes.
Many thanks in advance.

**Comment by georgulbrich-isg** [comment]
Hello mpacher,

we will look into alternative ways of syntax highlighting, without forcing the user to switch themes.

Thank you for your suggestion and best regards,
Georg Ulbrich

**Comment by lukashettler-isg** [comment]
@mpacher 

In https://github.com/isg-stuttgart/vscode-isg-cnc/pull/22 we discuss about the default syntax highlighting groups. Would you agree with these groups or do you have other ideas or wishes how the groups should be defined?
