### ISSUE TITLE
isg-commands not found before open nc-file

### ISSUE THREAD

**Issue by jurekseverin-isg** [isg-stuttgart/vscode-isg-cnc#30]
**Describe the bug**
If you open a new folder for the first time (or you have no folder opened), while the extension is enabled you cannot call the extension ISG-commands until you open a .nc-file (maybe also some other filetypes but .txt for example did NOT work). If you try call an extension command before doing so an error is thrown: Example: "Command 'ISG-CNC: Find next TFS code' resulted in an error (command 'isg-cnc.FindNextTFS' not found)".
Somehow if you open an .nc file, then close it and then try to use an isg-command there is no error, just no reaction.

**To Reproduce**
1. Make sure to have the extension enabled
2. Optional: Open a folder
3. Press ctrl+shift+P and call any isg-command
4. See Error: "Command<commandnameForUser> resulted in an error (command <commandnameIntern> not found)". <commandnameForUser> and <commandnameIntern> are placeholders for the specific commands.
5. Open .nc file
6. Press ctrl+shift+P and call any isg-command
7. See expected command behaviour
8. close .nc file
9.  Press ctrl+shift+P and call any isg-command
10. See no reaction (like expected if the command is used for .nc files)

**Expected behavior**
Of course most of these commands aren't useful to call without a nc file being open. However there should not be a "not found error" but just no reaction or maybe a message like " <commandname> can only be used with an opened .nc file".

**Comment by jurekseverin-isg** [comment]
- I fixed this while implementing in #16

**Comment by lukashettler-isg** [comment]
Hi Jurek, the description of this bugfix is missing in the Changelog.md-File. Can you please add this in the develop branch. Thank you

**Comment by jurekseverin-isg** [comment]
> Hi Jurek, the description of this bugfix is missing in the Changelog.md-File. Can you please add this in the develop branch. Thank you

Hi Lukas, i added this in the develop branch.
