### ISSUE TITLE
Why Configuration Setting for docu-path and default browser?

### ISSUE THREAD

**Issue by jurekseverin-isg** [isg-stuttgart/vscode-isg-cnc#32]
**Describe the bug**
The Extension Configuration Settings contain an "Documentation" setting where you can define the path to the ISG documentation.
This is never used in the extension and also not useful because why would you re-define it?

**Suggestion**
Just remove this Configuration Setting

**Comment by jurekseverin-isg** [comment]
Same goes with "Browser-linux" and "Browser-windows" configurations. They are never used. Furthermore the npm open package recognizes the users default browser. So there shouldn't be a use-case for these configurations in the future too.

**Comment by lukashettler-isg** [comment]
Hi Jurek,

the reason for the setting for the path to the ISG Documentation is that you can reference to a local Documentation if you don't have internet connection. This setting is useful and shouldn't be deleted. But I can't remember the reason for the Browser setting so this can be deleted in my opinion.

**Comment by jurekseverin-isg** [comment]
Thanks for feedback. I have only removed the Browser-paths now

**Comment by lukashettler-isg** [comment]
@jurekseverin-isg 
Can you please verify that the changes are merged into the develop branch.

**Comment by jurekseverin-isg** [comment]
> @jurekseverin-isg Can you please verify that the changes are merged into the develop branch.

The changes were merged succesfully into the develop branch by this Pull-request:
https://github.com/isg-stuttgart/vscode-isg-cnc/pull/36
