### ISSUE TITLE
an indentation after coments and cycle calls 

### ISSUE THREAD

**Issue by rosariotaormina-isg** [isg-stuttgart/vscode-isg-cnc#45]
if you deliberately design the indentations so that you can collapse certain blocks and then use the "ISG-CNC: Format Code" function, these indentations will be discarded again. It would be nice if these indentations were created when this function is executed.
it would be helpful if after comments and after cycle calls an indentation is generated.

**Before executing the function:**

![Format Code 1](https://user-images.githubusercontent.com/101697940/181515037-efc37cc9-12ac-4bdf-afa9-91077f876dfc.png)

**After executing the function:**

![Format Code 2](https://user-images.githubusercontent.com/101697940/181515180-10442d8f-4bc8-4e4d-aca6-f51c258d5f8f.png)

**Comment by andreas-hafner** [comment]
You can also indent the next line whenever \ (first time, then save state) is used. You would then only have to remember the status and when the next sentence is then recognized without \, then again one level back with the indentation. Like the comment state.

**Comment by lukashettler-isg** [comment]
Hi @andreas-hafner ,

thank you for your proposed solution. This should solve one problem of this issue. 
For the other problem we discussed that we want to create "commands" for users to mark the start and end for indentation. For example ; [INDENT] and ; [END INDENT].

**Comment by andreas-hafner** [comment]
> Hi @andreas-hafner ,
> 
> thank you for your proposed solution. This should solve one problem of this issue. For the other problem we discussed that we want to create "commands" for users to mark the start and end for indentation. For example ; [INDENT] and ; [END INDENT].

Hello @lukashettler-isg ,
I think this is not a good solution to force the user marking the indentation of the nc code with more commands. I think it is clear when the nc code should be indent or not. I also think nobody will use commands to set indent markers.

**Comment by andreas-hafner** [comment]
> > 
> 
> Hi @andreas-hafner, if you look in the issue description of @rosariotaormina-isg, he wants to indent after the comment `;cycle call` in the image. ![grafik](https://user-images.githubusercontent.com/85152900/189659030-45452026-b479-48dc-a139-77a8bef47060.png) He wants to use this feature to fold parts of the nc-program and only see the comment. I agree with you that the indentation after `L CYCLE[...]` is clear and there is no need for the user to mark this in a special comment.

Hi again @lukashettler-isg,
I don't know why you want to indent line 119, there is no reason for that. I don't think indentation is appropriate anywhere after comments. The indentation of the L CYCLE command would be a special case here in my opinion and should not be included in the standard. We could try to teach the folding that commands that go over multiple lines can be folded. For example L CYCLE can be folded until another line without break comes, so until the last line with backslash. Is this an idea, that you can think about?

;cycle name
L CYCLE [.......]  ; this is all folded
G00 Z100

best regards
Andreas

**Comment by jurekseverin-isg** [comment]
This was done in the branch linked above.
