### ISSUE TITLE
enhance file parser for line breaks

### ISSUE THREAD

**Issue by isg-stuttgart-github** [isg-stuttgart/vscode-isg-cnc#51]
**Describe the bug**

If a NC-file contain line breaks with `\` the parser for the side bar view can't parse the file correctly.

**Comment by jurekseverin-isg** [comment]
Also enhance it for %-commands

**Comment by jurekseverin-isg** [comment]
This was done while working on https://github.com/isg-stuttgart/vscode-isg-cnc/tree/beautify-via-parser.
