### ISSUE TITLE
isg-commands didnt work on linux system

### ISSUE THREAD

**Issue by andreas-hafner** [isg-stuttgart/vscode-isg-cnc#56]
**Describe the bug**
There is no effect if I run any command in context menu or in command line.

**To Reproduce**
Right click for context menu
Click on isg-commands
Click any command you like

**Expected behavior**
running the command

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - 
![vscode-isg-cnc](https://user-images.githubusercontent.com/99172551/186383185-86275fa1-f971-45e8-8e55-72cb2620552c.png)

**Comment by lukashettler-isg** [comment]
Thank you @andreas-hafner for reporting this issue. The behaviour is the same in Windows. We search the solution for this problem.

**Comment by lukashettler-isg** [comment]
hi @andreas-hafner we got the extension working again in the new version V0.3.4 but we had to temporarily remove the "start ISG documentation" feature, because this causes the problem. We will fix this in the next version V0.3.5.

**Comment by andreas-hafner** [comment]
thank you!
