### ISSUE TITLE
Bug with "format code" function on blocs number with colon

### ISSUE THREAD

**Issue by AurelWM** [isg-stuttgart/vscode-isg-cnc#6]
**Bug observed**
Hallo, 
Thank you for this extension, I just discovered it and I clean my *.nc programs for a Beckhoff CNC with your function "format code".
I observed the following bug:
If in a program there is a label followed by a colon like:
N10:
The function "format code" add space between label and colon like:
N10   : 
And then if you execute "format code" once again, it add again space.

**Screenshots**
Initial state:
![image](https://user-images.githubusercontent.com/94175716/141467466-182ef997-8a6e-4ff7-b07b-370c1a5e3588.png)

First execution of "format code":
![image](https://user-images.githubusercontent.com/94175716/141467598-9b6c0aee-7694-40f5-8f99-e836f565fd55.png)

Second execution of "format code":
![image](https://user-images.githubusercontent.com/94175716/141467646-cdb64603-dc92-4df4-a35d-1c65c8f078e2.png)

Thank you, best regards

**Comment by AurelWM** [comment]
A important information: it occurs only if the bloc number is inside an indented area.
Between $IF and $ENDIF for example.

**Comment by andreashafner-isg** [comment]
Hello @AurelWM,
thank you for reporting the bug and for using the extension. 
I confirmed the bug and I will fix it as soon as possible.

Thank you and best regards.
Andreas

**Comment by andreashafner-isg** [comment]
Fixed in [release version v0.2.4](https://github.com/isg-stuttgart/vscode-isg-cnc/releases/tag/V0.2.4)
