### ISSUE TITLE
Block numbers in combination with skip lines

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#76]
Die Integration von automatischen Satznummern funktioniert gut und wird auch permanent benutzt.
Bei Verwenden von Skipping müssen die Zeilen, die ausgeblendet werden sollen, im Nachgang manuell bearbeitet werden.
Vorher:

```
%skip_test.nc
G0 X0 Y0 Z0
G1 F100
G1 X2
#TIME 2
#FLUSH WAIT
/Z3
#TIME 2
G1 X4
#FLUSH WAIT
/Y2
X6

M30
```
Nachher:

```
%skip_test.nc
N010 G0 X0 Y0 Z0
N020 G1 F100
N030 G1 X2
N040 #TIME 2
N050 #FLUSH WAIT
N060 /Z3
N070 #TIME 2
N080 G1 X4
N090 #FLUSH WAIT
N100 /Y2
N110 X6

N120 M30
```

Anwenderfreundlich wäre das Ergebnis:
**/N060 Z3**

**Comment by jurekseverin-isg** [comment]
@lukashettler-isg sollten Zuweisungszeilen in #VAR-#ENDVAR Böcken nummeriert werden?
Also soll 
```
#VAR
V.L.SurfacePosition = 0
#ENDVAR
```
zu
```
N010 #VAR
N020 V.L.SurfacePosition = 0
N030 #ENDVAR
```
oder zu 
```
N010 #VAR
V.L.SurfacePosition = 0
N020 #ENDVAR
```
werden? Oder nochmal anders?

**Comment by jurekseverin-isg** [comment]
I will also replace current Insertion Position by using the parser instead of regexs and indexOf. This allows more flexibility e.g. if you already have a blocknumber behing "/" which should be replaced.

**Comment by jurekseverin-isg** [comment]
Closed by https://github.com/isg-stuttgart/vscode-isg-cnc/pull/94
