### ISSUE TITLE
Dont add block numbers to multilines

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#81]
**Describe the bug**

When using the "add block numbers" function of the extension the function also generate block numbers in multilines. This will lead to an invalid NC-program and should be avoided.

**To Reproduce**

Use the  "add block numbers" function in the following program code:

```
L CYCLE [NAME= asd @P1=20\
  @P2 =10]
```

**Expected behavior**

The result is:
```
N030 L CYCLE [NAME= asd @P1=20\
N040   @P2 =10]
```

but should be:

```
N030 L CYCLE [NAME= asd @P1=20\
            @P2 =10]
```

**Comment by lukashettler-isg** [comment]
> @lukashettler-isg sollten Zuweisungszeilen in #VAR-#ENDVAR Böcken nummeriert werden? Also soll
> 
> ```
> #VAR
> V.L.SurfacePosition = 0
> #ENDVAR
> ```
> 
> zu
> 
> ```
> N010 #VAR
> N020 V.L.SurfacePosition = 0
> N030 #ENDVAR
> ```
> 
> oder zu
> 
> ```
> N010 #VAR
> V.L.SurfacePosition = 0
> N020 #ENDVAR
> ```
> 
> werden? Oder nochmal anders?

Bitte komplett nummerieren. Also so wie du gesagt hast:

N010 #VAR
N020 V.L.SurfacePosition = 0
N030 #ENDVAR

**Comment by jurekseverin-isg** [comment]
Closed with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/84
