### ISSUE TITLE
Cursor position after insert a region/endregion block

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#82]
# problem description

When inserting a region/endregion by using the snippet, the cursor is behind `;endregion`. It would be better if the cursor is behind `;region` that you can continue writing.

**Comment by jurekseverin-isg** [comment]
Closed by https://github.com/isg-stuttgart/vscode-isg-cnc/pull/83

**Comment by jurekseverin-isg** [comment]
Miscommunication:
I let the cursor and within the block but it's better to let in end in the same line to type region-description

**Comment by jurekseverin-isg** [comment]
Closed again by https://github.com/isg-stuttgart/vscode-isg-cnc/pull/86
