### ISSUE TITLE
Add language server to VS-Code Extension

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#90]
## Desired behaviour

It would be a helpful feature if it's possible to use shortcuts like F12 for "Go to definition" in NC-programs. This could be used for all kind of variables like V.L., V.P. etc. Also for CYCLE calls it would be a good feature.

A description for implementing such a language server can be found [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide)

**Comment by jurekseverin-isg** [comment]
"Go to Definition" for program calls, goto-statements and self-defined variables added as first language server feature within https://github.com/isg-stuttgart/vscode-isg-cnc/pull/106
