### ISSUE TITLE
Display of sidebar in files without .nc or .cyc ending

### ISSUE THREAD

**Issue by lukashettler-isg** [isg-stuttgart/vscode-isg-cnc#92]
**Describe the bug**

There can be NC-programs without the typical ending .nc or .cyc. For these files the CNC language can be set manually in VS-Code. After a file is set to CNC language the sidebar should display the tool and cycle calls. At the moment there is only the text `the currently opened file is no CNC-file` If it would be possible to set all files in a folder to CNC language that would be a good feature too.

**Example**

![grafik](https://user-images.githubusercontent.com/85152900/205648721-5ce23392-3596-49cb-a3b3-88c383d9c341.png)

**Comment by jurekseverin-isg** [comment]
Done with https://github.com/isg-stuttgart/vscode-isg-cnc/pull/96
