### ISSUE TITLE
Command 'ISG-CNC: Add Blocknumbers' resulted in an error (Illegal value for `line`)

### ISSUE THREAD

**Issue by lukashochuli-gfms** [isg-stuttgart/vscode-isg-cnc#93]
Die Funktion "Add Blocknumbers" ist eine sehr hilfreiche Funktionalität. Werden nach dem letzten Speichern der Datei die Anzahl Zeilen verändert, kann dies zu einem Fehler führen:

![Fehler illegal value for line](https://user-images.githubusercontent.com/120000738/206168626-0508656f-af1a-4624-a5c5-b9f8813f5b2b.png)

Dazu muss folgender ISO-Code in einem File gespeichert werden, zwei Zeilen vom Ende des Files gelöscht und anschliessend das Kommando "Add Blocknumbers" ausgeführt werden:

```
%blocknumbers.nc
G0 X0 Y0 Z0
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
G91 G0 X0.1
M30
```

**Comment by jurekseverin-isg** [comment]
Das Problem lag vermutlich daran, dass bisher die im File System gespeicherte Datei als Grundlage für das Hinzufügen der Blocknumbers herangezogen wurde.
Durch https://github.com/isg-stuttgart/vscode-isg-cnc/pull/94 wurde nun eh die Add-Blocknumbers Funktion umstrukturiert.
Der Fehler lässt sich mit den Änderungen nicht reproduzieren und sollte daher mit dem nächsten Release behoben sein
